trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  group: 'employee-app-variable-group'
  buildConfiguration: 'Release'
  nodeVersion: '20.x'

stages:

# ==========================
# Build Stage
# ==========================
- stage: Build
  displayName: 'Build Stage'

  jobs:
  - job: BuildJob
    displayName: 'Build Application'

    steps:

    # Install .NET 8
    - task: UseDotNet@2
      displayName: 'Install .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'

    # Restore
    - task: DotNetCoreCLI@2
      displayName: 'Restore Packages'
      inputs:
        command: 'restore'
        projects: 'server/*.sln'

    # Build
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: 'server/*.sln'
        arguments: '--configuration $(buildConfiguration)'

    # Publish API
    - task: DotNetCoreCLI@2
      displayName: 'Publish API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'server/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'

    # Install Node
    - task: UseNode@1
      displayName: 'Install Node.js'
      inputs:
        version: '$(nodeVersion)'

    # Install Angular Packages
    - script: |
        cd client
        npm install
      displayName: 'Install npm packages'

    # Build Angular
    - script: |
        cd client
        npm run build
      displayName: 'Build Angular'

    # Publish Artifact
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Artifact'
      inputs:
        targetPath: 'client/dist'
        ArtifactName: 'clientArtifact'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'serverArtifact'


# ==========================
# Deploy API
# ==========================
- stage: Deploy_Dev
  displayName: 'Deploy Development'
  dependsOn: Build

  jobs:

  - deployment: DeployAPI
    displayName: 'Deploy API'
    environment: Development

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: serverArtifact

          - task: AzureWebApp@1
            displayName: 'Deploy API'

            inputs:
              azureSubscription: 'AzureConnection'
              appType: webApp
              appName: 'employee-api-abdulrahim'
              package: '$(Pipeline.Workspace)/serverArtifact/**/*.zip'

# ==========================
# Deploy Client
# ==========================
- stage: Deploy_Client

  displayName: 'Deploy Angular'

  dependsOn: Deploy_Dev

  jobs:

  - job: DeployAngular
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - download: current
      artifact: clientArtifact

    - task: AzureStaticWebApp@0
      displayName: 'Deploy Angular'

      inputs:

        app_location: '$(Pipeline.Workspace)/clientArtifact/dssiui/browser'

        output_location: ''

        skip_app_build: true

        azure_static_web_apps_api_token: $(StaticWebAppToken)