trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  nodeVersion: '20.x'

steps:

# Install .NET 8 SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'server/*.sln'

# Build solution
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'server/*.sln'
    arguments: '--configuration $(buildConfiguration)'

# Publish API
- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'server/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'

# Install Node.js
- task: UseNode@1
  inputs:
    version: '20.x'

# Install Angular dependencies
- script: |
    cd client
    npm install
  displayName: 'Install npm packages'

# Build Angular
- script: |
    cd client
    npm run build
  displayName: 'Build Angular'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'